Module2-task1
htmlacademy-vue/777003-pizza-1 pull request #2
Opened 2022-02-10 09:27 UTC by katokdoescode

Без глобального стейта данные передаются по цепочке между компонентами:
Все ингредиенты > BuilderIngredientsSelector > RadioButton > Любое изменение количества > BuilderIngredientsSelector > Index > BuilderPizzaView > BuilderPizzaPriceCounter

Для drag'n'drop событие дропа с данными на BuilderPizzaView эммитится обратно в BuilderIngredientsSelector, а от туда расходится по вложенным компонентам

addIngredient и removeIngredient хотелось бы объеденить в один метод, так как они очень похожи, но как ни крути пришлось бы dataset раздувать при эммитировании событий.
Не совсем понимаю как в таких случая правильней поступать.

А так же отделил бы методы getIngredientClass, getIngredientName и getPizzaSize в какой-нибудь внешний хэлпер.
Насколько я понимаю обычно mixins для этого используются. В будущем лучше использовать mixins или пробовать в файд хелпера выносить?

2022-02-10 12:27 UTC, enotke requested changes

2022-02-10 12:27 UTC, enotke commented on src/frontend/src/layouts/AppLayout.vue
> +    Сама идея лэйаутов понятно, но как переключаться между ними тогда?
В Vue из коробки нет способа изменять layout, сделать это можно разными способами достаточно просто, в следующих уроках эта тема будет затронута. Например в Nuxt из коробки можно менять дефолтный layout. В целом это довольно полезная штука

2022-02-10 12:27 UTC, enotke commented on src/frontend/src/views/Index.vue
> +        this.selectedPizzaParameters.selectedIngredients[ingredientId].count++;
Максимальное количество одинаковых ингредиентов на пицце — 3.

2022-02-10 12:27 UTC, enotke commented on src/frontend/src/views/Index.vue
> +          this.selectedPizzaParameters.selectedIngredients,
Вот это можно вынести в один метод и объединить с addIngredient

2022-02-10 12:27 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +      <div class="pizza pizza--foundation--big-tomato">
Выбор теста и размера тоже влияет на внешний вид пиццы

2022-02-10 12:27 UTC, enotke commented on src/frontend/src/views/Index.vue
> -      order: {
У тебя же раньше правильно было. Нужно хранить именно выбранные параметры пиццы, а сумму можно и посчитать

2022-02-10 12:27 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +          <template v-slot>
Темплейт тут не нужен, он же у тебя один

2022-02-10 12:27 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +          :radioBtnClass="['visually-hidden']"
Плохая практика. У тебя стили глобальные, поэтому всё работает, но по хорошему стили должны быть изолированными. И этот параметр везде добавляет класс .visually-hidden. Лучше сделать параметр hidden и отталкиваться в компоненте от него

2022-02-10 12:27 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +          radioBtnName="dought"
И так понятно, что это название кнопки, лучше назвать эти параметры: name, value....

2022-02-10 12:27 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +      selectedDoughPrice: null,
Тут вообще не нужно хранить стоимость, лучше сразу обновлять это значение в компоненте Index

2022-02-10 12:27 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +            <template v-slot>
То же самое, template тут не нужен

2022-02-10 12:27 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +                @counterMinus="$emit('removeIngredient', ingredient.id)"
Можно обновить всё в один метод changeCount

2022-02-10 12:27 UTC, enotke commented on src/frontend/src/views/Index.vue
> +          this.selectedPizzaParameters.selectedIngredients,
В целом лучше сразу передавать из селектора конечное значение, а тут его просто присваивать. Тогда всё станет гораздо проще. Почитай про модификатор .sync или про v-model

2022-02-10 12:27 UTC, enotke commented on src/frontend/src/views/Index.vue
> +            price: this.pizza.ingredients[ingredientId - 1].price,
То что у тебя Id ингредиентов идут по порядку это просто совпадение. Нужно искать этот ингредиент в списке именно по Id ингредиента, а не по Id массива

2022-02-10 12:27 UTC, enotke commented on src/frontend/src/views/Index.vue
> +            total += ingredient.price * ingredient.count;
обычно такое делают через Array.reduce

2022-02-10 12:27 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +      return ingredients.filter((ingredient) => ingredient.count != 0);
Желательно использовать строгие сравнения

2022-02-10 12:27 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderSizeSelector.vue
> +      switch (size.multiplier) {
Лучше уж опираться на Id, а не множитель

2022-02-10 12:27 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderSizeSelector.vue
> +      selectedSizeMultiplier: null,
Тут тоже ничего не нужно хранить

2022-02-10 12:27 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderSizeSelector.vue
> +      required: true,
Так как ты не выделяешь элементы списка в отдельные компоненты, то элементы списка можно валидировать через параметр validate в пропсе

2022-02-10 12:27 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +                    ? selectedIngredients[ingredient.id].count
Такую логику лучше выносить в методы

2022-02-10 12:27 UTC, enotke commented on src/frontend/src/common/components/DragWrapper.vue
> +    :draggable="true"
Лучше просто <div draggable />

2022-02-10 14:07 UTC, katokdoescode commented
@enotke Спасибо за подробности!
Многие вещи в которых были сомнения стали более ясны.

2022-02-15 14:50 UTC, katokdoescode commented on src/frontend/src/modules/builder/components/BuilderSizeSelector.vue
> +      required: true,
Не очень понял, а что там валидировать?
Проверить, есть ли в массиве объекты?

2022-02-15 14:54 UTC, katokdoescode commented on src/frontend/src/views/Index.vue
> +          this.selectedPizzaParameters.selectedIngredients,
объединил все в один метод.
Попробовал использовать v-model и .sync, но если честно никаких результатов это не дало, сначала только все еще сильнее усложнило.
.sync не умеет привязываться к вложенным в Object переменным как я понял, а v-model работает с переменными в data(), у меня они хранятся только в Index.vue, и получается вроде как и бесполезно для вложенных компонентов.

2022-02-15 15:05 UTC, katokdoescode commented on src/frontend/src/views/Index.vue
> +            total += ingredient.price * ingredient.count;
Через reduce там не очень получилось, решил оставить как есть

2022-02-15 21:26 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderSizeSelector.vue
> +      required: true,
С помощью функции validator можно например проверить, что в этих объектах есть поля id и multiplier

2022-02-15 21:41 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +            :key="'on-pizza-ingredient-' + getIngredientName(ingredient)"
В зависимости от количества ингредиентов класс должен меняться на pizza__filling--second,  pizza__filling--third

2022-02-15 21:57 UTC, enotke commented on src/frontend/src/views/Index.vue
> +        if (typeof data === "boolean") {
Как-то всё очень сложно. На самом деле всё это делается гораздо проще. Нужно в самом инпуте при изменении количества передавать id ингредиента и итоговое количество. Тогда тут можно будет просто присвоить это значение

2022-02-15 22:21 UTC, enotke requested changes
В целом сделано хорошо. Нужно только поработать с изменением количества ингредиентов

2022-02-15 22:21 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +  name: "PizzaView",
Название файла должно соответствовать названию компонента

2022-02-15 22:21 UTC, enotke commented on src/frontend/src/views/Index.vue
> +        if (typeof data === "boolean") {
Просто ты всё подряд добавляешь в selectedIngredients. Можно сделать так. Добавить IngredientList - список доступных ингредиентов. И selectedIngredients в формате {ingredientId: ingredientCount}. Тогда можно будет гораздо проще обновлять количество. Должно быть что-то типо такого this.$set(this.selectedIngredients, id, count). А список ингредиентов для пиццы можно будет получать через computed свойство

2022-02-15 22:21 UTC, enotke commented on src/frontend/src/views/Index.vue
> +        if (typeof data === "boolean") {
Если что-то непонятно можешь писать в телеграм id - `@Enotke`. Или записываться на консультацию

2022-02-15 22:21 UTC, enotke commented on src/frontend/src/views/Index.vue
>    name: "Constructor",
Опять же. Имена файлов и имена компонентов должны быть одинаковыми

2022-02-17 08:25 UTC, katokdoescode commented on src/frontend/src/views/Index.vue
> +        if (typeof data === "boolean") {
@enotke Я так усложнил, потому что не смог додуматься, как передать новое значение инпута по нажатию на кнопку в ItemCounter, по этому в родительском компоненте производил все манипуляции, и по цепочке передавал полный массив объектов с ингредиентами.
Я понял в чем проблема такого метода, так почти невозможно выполнить условие с добавлением класса второму и третему ингредиенту для пиццы.

Сейчас я нашел нормальный способ, буду рефакторить. Общую идею я наконец-то понял)

2022-03-29 08:42 UTC, merged