Маршрутизатор и лейауты
htmlacademy-vue/777003-pizza-1 pull request #4
Opened 2022-03-30 15:30 UTC by katokdoescode

Создал затычки для страниц
Для авторизации добавил неотформатированный шаблон в качестве затычки.
Добавил примитивную логику для шапки, чтобы соотвествовать пункту 3.7 т.з.
Шаблоны подключаются автоматически, по умолчанию устанавливается основной лэйаут.

---
:mortar_board: [Маршрутизатор и лейауты](https://up.htmlacademy.ru/vue/1/user/777003/tasks/4)

2022-03-30 21:38 UTC, enotke requested changes

2022-03-30 21:38 UTC, enotke commented on src/frontend/src/layouts/AppLayout.vue
> +    <slot />
Как-то странно. Вот этот слот нигде не устанавливается и не используется в шаблонах

2022-03-30 21:38 UTC, enotke commented on src/frontend/src/layouts/AppLayout.vue
> +    <slot />
И ещё у тебя есть один баг. Кнопка "Готовьте!" должна быть активной если было введено название пиццы и выбраны ингредиенты

2022-03-31 07:55 UTC, katokdoescode commented on src/frontend/src/layouts/AppLayout.vue
> +    <slot />
Проверил еще раз, получается в моем случае слот вообще не нужен. AppLayout просто будет выполнять роль автоматического шаблона, подставляя дефолтный шаблон, либо тот который указан в meta роута.

2022-03-31 08:34 UTC, katokdoescode commented
@enotke Добавил валидацию по цене и названию пиццы.

2022-03-31 20:48 UTC, merged